
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/billing_system_db?forceBinary=false&options=-c%20timezone=UTC
spring.datasource.username=billing_user
spring.datasource.password=billing_password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true